// AUTO-GENERATED by tools/gen-tables from ibm-1399_P110-2003.ucm — DO NOT EDIT.
// SBCS 部と DBCS 部を合成するだけ。表の実体はそれぞれの隣のファイルにある。
// Mapping data: ICU (unicode-org/icu-data), License: Unicode License V3 (tools/gen-tables/ucm/LICENSE).
// 再生成: npm run gen:tables
import type { StatefulTable } from "../table-types.js";
import { ibm1399Sbcs } from "./ibm1399-sbcs.js";
import { ibm1399Dbcs } from "./ibm1399-dbcs.js";

export const ibm1399: StatefulTable = {
  ccsid: 1399,
  name: "ibm-1399_P110-2003",
  sbcs: ibm1399Sbcs,
  dbcs: ibm1399Dbcs
};
