// AUTO-GENERATED by tools/gen-tables from ibm-939_P120-1999.ucm — DO NOT EDIT.
// SBCS 部と DBCS 部を合成するだけ。表の実体はそれぞれの隣のファイルにある。
// Mapping data: ICU (unicode-org/icu-data), License: Unicode License V3 (tools/gen-tables/ucm/LICENSE).
// 再生成: npm run gen:tables
import type { StatefulTable } from "../table-types.js";
import { ibm939Sbcs } from "./ibm939-sbcs.js";
import { ibm939Dbcs } from "./ibm939-dbcs.js";

export const ibm939: StatefulTable = {
  ccsid: 939,
  name: "ibm-939_P120-1999",
  sbcs: ibm939Sbcs,
  dbcs: ibm939Dbcs
};
