// AUTO-GENERATED by tools/gen-tables from ibm-930_P120-1999.ucm — DO NOT EDIT.
// SBCS 部と DBCS 部を合成するだけ。表の実体はそれぞれの隣のファイルにある。
// Mapping data: ICU (unicode-org/icu-data), License: Unicode License V3 (tools/gen-tables/ucm/LICENSE).
// 再生成: npm run gen:tables
import type { StatefulTable } from "../table-types.js";
import { ibm930Sbcs } from "./ibm930-sbcs.js";
import { ibm930Dbcs } from "./ibm930-dbcs.js";

export const ibm930: StatefulTable = {
  ccsid: 930,
  name: "ibm-930_P120-1999",
  sbcs: ibm930Sbcs,
  dbcs: ibm930Dbcs
};
