import type { UcmFile } from "./ucm.js";

/**
 * SBCS .ucm → core の SbcsTable モジュール（TS ソース）を生成する。
 * 方向規則: EBCDIC→Unicode は flag 0|3、Unicode→EBCDIC は flag 0|1 を採用（|2 subchar1 は捨てる）。
 */
export function emitSbcsTable(ucm: UcmFile, opts: { ccsid: number; exportName: string; sourceFile: string }): string {
  if (ucm.header.uconvClass !== "SBCS") {
    throw new Error(
      `expected SBCS .ucm, got ${ucm.header.uconvClass} (${ucm.header.codeSetName}) — EBCDIC_STATEFUL は subtask 04 で対応`
    );
  }
  const sub = ucm.header.subchar[0];
  if (sub === undefined) throw new Error("missing <subchar>");

  const e2u: number[] = []; // flat [byte, uni, ...]
  const u2e: number[] = []; // flat [uni, byte, ...]
  for (const e of ucm.entries) {
    const byte = e.bytes[0];
    if (byte === undefined || e.bytes.length !== 1) {
      throw new Error(`SBCS entry with ${e.bytes.length} bytes`);
    }
    if (e.flag === 0 || e.flag === 3) e2u.push(byte, e.unicode);
    if (e.flag === 0 || e.flag === 1) u2e.push(e.unicode, byte);
  }

  const fmt = (nums: number[], per: number): string => {
    const lines: string[] = [];
    for (let i = 0; i < nums.length; i += per) {
      lines.push(
        "  " +
          nums
            .slice(i, i + per)
            .map((n) => "0x" + n.toString(16))
            .join(", ")
      );
    }
    return lines.join(",\n");
  };

  return `// AUTO-GENERATED by tools/gen-tables from ${opts.sourceFile} — DO NOT EDIT.
// Mapping data: ICU (unicode-org/icu-data), License: Unicode License V3 (tools/gen-tables/ucm/LICENSE).
// 再生成: npm run gen:tables
import type { SbcsTable } from "../table-types.js";

const E2U: number[] = [
${fmt(e2u, 8)}
];
const U2E: number[] = [
${fmt(u2e, 8)}
];

const ebcdicToUnicode = new Uint16Array(256).fill(0xfffd);
for (let i = 0; i < E2U.length; i += 2) ebcdicToUnicode[E2U[i]!] = E2U[i + 1]!;
const unicodeToEbcdic = new Map<number, number>();
for (let i = 0; i < U2E.length; i += 2) unicodeToEbcdic.set(U2E[i]!, U2E[i + 1]!);

export const ${opts.exportName}: SbcsTable = {
  ccsid: ${opts.ccsid},
  name: ${JSON.stringify(ucm.header.codeSetName)},
  ebcdicToUnicode,
  unicodeToEbcdic,
  sub: 0x${sub.toString(16)}
};
`;
}
