import type { UcmFile } from "./ucm.js";

/**
 * EBCDIC_STATEFUL .ucm（ibm-930/939/1399）→ core の StatefulTable モジュール（TS ソース）を生成する。
 * 1 バイトエントリ = SBCS 部（SI モード）、2 バイトエントリ = DBCS 部（SO モード）に振り分ける。
 * 方向規則: EBCDIC→Unicode は flag 0|3、Unicode→EBCDIC は flag 0|1（|2 subchar1 は捨てる）。
 */
export function emitStatefulTable(
  ucm: UcmFile,
  opts: { ccsid: number; exportName: string; sourceFile: string }
): string {
  if (ucm.header.uconvClass !== "EBCDIC_STATEFUL") {
    throw new Error(`expected EBCDIC_STATEFUL, got ${ucm.header.uconvClass} (${ucm.header.codeSetName})`);
  }
  const sbcsSub = 0x3f; // SBCS SUB（<subchar1> は 0x3F）

  const sbcsE2U: number[] = []; // [byte, uni, ...]
  const sbcsU2E: number[] = [];
  const dbcsE2U: number[] = []; // [(b1<<8|b2), uni, ...]
  const dbcsU2E: number[] = [];

  for (const e of ucm.entries) {
    if (e.bytes.length === 1) {
      const b = e.bytes[0]!;
      if (e.flag === 0 || e.flag === 3) sbcsE2U.push(b, e.unicode);
      if (e.flag === 0 || e.flag === 1) sbcsU2E.push(e.unicode, b);
    } else if (e.bytes.length === 2) {
      const packed = (e.bytes[0]! << 8) | e.bytes[1]!;
      if (e.flag === 0 || e.flag === 3) dbcsE2U.push(packed, e.unicode);
      if (e.flag === 0 || e.flag === 1) dbcsU2E.push(e.unicode, packed);
    }
    // 3 バイト以上は EBCDIC_STATEFUL には現れない
  }

  const fmt = (nums: number[]): string => {
    const lines: string[] = [];
    for (let i = 0; i < nums.length; i += 10) {
      lines.push("  " + nums.slice(i, i + 10).map((n) => n.toString()).join(","));
    }
    return lines.join(",\n");
  };

  return `// AUTO-GENERATED by tools/gen-tables from ${opts.sourceFile} — DO NOT EDIT.
// Mapping data: ICU (unicode-org/icu-data), License: Unicode License V3 (tools/gen-tables/ucm/LICENSE).
// 再生成: npm run gen:tables
import type { StatefulTable } from "../table-types.js";

const SB_E2U: number[] = [
${fmt(sbcsE2U)}
];
const SB_U2E: number[] = [
${fmt(sbcsU2E)}
];
const DB_E2U: number[] = [
${fmt(dbcsE2U)}
];
const DB_U2E: number[] = [
${fmt(dbcsU2E)}
];

const sbEbcdicToUnicode = new Uint16Array(256).fill(0xfffd);
for (let i = 0; i < SB_E2U.length; i += 2) sbEbcdicToUnicode[SB_E2U[i]!] = SB_E2U[i + 1]!;
const sbUnicodeToEbcdic = new Map<number, number>();
for (let i = 0; i < SB_U2E.length; i += 2) sbUnicodeToEbcdic.set(SB_U2E[i]!, SB_U2E[i + 1]!);
const dbEbcdicToUnicode = new Map<number, number>();
for (let i = 0; i < DB_E2U.length; i += 2) dbEbcdicToUnicode.set(DB_E2U[i]!, DB_E2U[i + 1]!);
const dbUnicodeToEbcdic = new Map<number, number>();
for (let i = 0; i < DB_U2E.length; i += 2) dbUnicodeToEbcdic.set(DB_U2E[i]!, DB_U2E[i + 1]!);

export const ${opts.exportName}: StatefulTable = {
  ccsid: ${opts.ccsid},
  name: ${JSON.stringify(ucm.header.codeSetName)},
  sbcs: {
    ccsid: ${opts.ccsid},
    name: ${JSON.stringify(ucm.header.codeSetName + "_SBCS")},
    ebcdicToUnicode: sbEbcdicToUnicode,
    unicodeToEbcdic: sbUnicodeToEbcdic,
    sub: 0x${sbcsSub.toString(16)}
  },
  dbcs: {
    ebcdicToUnicode: dbEbcdicToUnicode,
    unicodeToEbcdic: dbUnicodeToEbcdic,
    sub: 0xfefe
  }
};
`;
}
