import type { UcmFile } from "./ucm.js";

/** 混在 CCSID 1 つあたりの生成物（3 モジュールに割る。理由は emitStatefulTable の JSDoc） */
export interface StatefulModules {
  /** SBCS 部だけ（`<name>Sbcs: SbcsTable`）。約 96 行 */
  sbcs: string;
  /** DBCS 部だけ（`<name>Dbcs: DbcsPart`）。表の約 98% がここ */
  dbcs: string;
  /** 上 2 つを合成するだけ（`<name>: StatefulTable`） */
  index: string;
}

/** 生成物すべてに付ける出典ヘッダ。分割しても出典が落ちない形にする */
function header(sourceFile: string, what: string): string {
  return `// AUTO-GENERATED by tools/gen-tables from ${sourceFile} — DO NOT EDIT.
// ${what}
// Mapping data: ICU (unicode-org/icu-data), License: Unicode License V3 (tools/gen-tables/ucm/LICENSE).
// 再生成: npm run gen:tables`;
}

/** 数値配列を 10 個ずつ改行して並べる（差分を読める幅に保つ） */
function fmt(nums: number[]): string {
  const lines: string[] = [];
  for (let i = 0; i < nums.length; i += 10) {
    lines.push("  " + nums.slice(i, i + 10).map((n) => n.toString()).join(","));
  }
  return lines.join(",\n");
}

/**
 * EBCDIC_STATEFUL .ucm（ibm-930/939/1399）→ StatefulTable を **3 モジュール**に分けて生成する。
 * 1 バイトエントリ = SBCS 部（SI モード）、2 バイトエントリ = DBCS 部（SO モード）に振り分ける。
 * 方向規則: EBCDIC→Unicode は flag 0|3、Unicode→EBCDIC は flag 0|1（|2 subchar1 は捨てる）。
 *
 * **なぜ 3 つに割るか。** 1 モジュールに詰めると、SBCS 部の 256 要素しか要らない利用者
 * （`katakanaChar`＝ブラウザの半角カナ表示）にも DBCS 部が付いてくる。
 * 実測で ibm930 は 4,794 行中 SBCS 部が約 2%・DBCS 部が約 98% で、
 * web-ui の本番バンドルに 930/939 の表が丸ごと入っていた。
 * bundler が落とせるのはモジュール単位なので、**割らなければ分けられない**。
 *
 * 割り方は型がそのまま示している——`StatefulTable` は元から
 * `sbcs: SbcsTable` と `dbcs: DbcsPart` の合成として定義されており、
 * データの置き方を型の構造に合わせるだけ（`table-types.ts` は変更していない）。
 */
export function emitStatefulTable(
  ucm: UcmFile,
  opts: { ccsid: number; exportName: string; sourceFile: string }
): StatefulModules {
  if (ucm.header.uconvClass !== "EBCDIC_STATEFUL") {
    throw new Error(`expected EBCDIC_STATEFUL, got ${ucm.header.uconvClass} (${ucm.header.codeSetName})`);
  }
  const sbcsSub = 0x3f; // SBCS SUB（<subchar1> は 0x3F）

  const sbcsE2U: number[] = []; // [byte, uni, ...]
  const sbcsU2E: number[] = [];
  const dbcsE2U: number[] = []; // [(b1<<8|b2), uni, ...]
  const dbcsU2E: number[] = [];

  for (const e of ucm.entries) {
    if (e.bytes.length === 1) {
      const b = e.bytes[0]!;
      if (e.flag === 0 || e.flag === 3) sbcsE2U.push(b, e.unicode);
      if (e.flag === 0 || e.flag === 1) sbcsU2E.push(e.unicode, b);
    } else if (e.bytes.length === 2) {
      const packed = (e.bytes[0]! << 8) | e.bytes[1]!;
      if (e.flag === 0 || e.flag === 3) dbcsE2U.push(packed, e.unicode);
      if (e.flag === 0 || e.flag === 1) dbcsU2E.push(e.unicode, packed);
    }
    // 3 バイト以上は EBCDIC_STATEFUL には現れない
  }

  const name = ucm.header.codeSetName;
  const sbcsName = JSON.stringify(name + "_SBCS");

  const sbcs = `${header(opts.sourceFile, `SBCS 部（SI モード・1 バイト）のみ。DBCS 部は ${opts.exportName}-dbcs.ts。`)}
import type { SbcsTable } from "../table-types.js";

const SB_E2U: number[] = [
${fmt(sbcsE2U)}
];
const SB_U2E: number[] = [
${fmt(sbcsU2E)}
];

const ebcdicToUnicode = new Uint16Array(256).fill(0xfffd);
for (let i = 0; i < SB_E2U.length; i += 2) ebcdicToUnicode[SB_E2U[i]!] = SB_E2U[i + 1]!;
const unicodeToEbcdic = new Map<number, number>();
for (let i = 0; i < SB_U2E.length; i += 2) unicodeToEbcdic.set(SB_U2E[i]!, SB_U2E[i + 1]!);

export const ${opts.exportName}Sbcs: SbcsTable = {
  ccsid: ${opts.ccsid},
  name: ${sbcsName},
  ebcdicToUnicode,
  unicodeToEbcdic,
  sub: 0x${sbcsSub.toString(16)}
};
`;

  const dbcs = `${header(opts.sourceFile, `DBCS 部（SO モード・2 バイト）のみ。SBCS 部は ${opts.exportName}-sbcs.ts。`)}
import type { DbcsPart } from "../table-types.js";

const DB_E2U: number[] = [
${fmt(dbcsE2U)}
];
const DB_U2E: number[] = [
${fmt(dbcsU2E)}
];

const ebcdicToUnicode = new Map<number, number>();
for (let i = 0; i < DB_E2U.length; i += 2) ebcdicToUnicode.set(DB_E2U[i]!, DB_E2U[i + 1]!);
const unicodeToEbcdic = new Map<number, number>();
for (let i = 0; i < DB_U2E.length; i += 2) unicodeToEbcdic.set(DB_U2E[i]!, DB_U2E[i + 1]!);

export const ${opts.exportName}Dbcs: DbcsPart = {
  ebcdicToUnicode,
  unicodeToEbcdic,
  sub: 0xfefe
};
`;

  const index = `${header(opts.sourceFile, "SBCS 部と DBCS 部を合成するだけ。表の実体はそれぞれの隣のファイルにある。")}
import type { StatefulTable } from "../table-types.js";
import { ${opts.exportName}Sbcs } from "./${opts.exportName}-sbcs.js";
import { ${opts.exportName}Dbcs } from "./${opts.exportName}-dbcs.js";

export const ${opts.exportName}: StatefulTable = {
  ccsid: ${opts.ccsid},
  name: ${JSON.stringify(name)},
  sbcs: ${opts.exportName}Sbcs,
  dbcs: ${opts.exportName}Dbcs
};
`;

  return { sbcs, dbcs, index };
}
